name: Deploy to Azure

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev
    
    defaults:
      run:
        working-directory: ./src
    
    steps:
    - name: Publish
      run: dotnet publish 'Api' -c Release -o '_api'
      
    - name: Deploy
      uses: azure/webapps-deploy@v2
      with: 
        app-name: exadelsandbox-officebooking-dev
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: './_api'
