name: Build and test

on:
  workflow_dispatch:
  pull_request_target:
    branches: [ main ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./src

    steps:
    - name: Verify Linked Issue
      uses: hattan/verify-linked-issue-action@v1.1.5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - uses: actions/cache@v2
      with:
        path: ~/.nuget/packages
        # Look to see if there is a cache hit for the corresponding requirements file
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget

    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build -c Release --no-restore
    
    - name: Test
      run: dotnet test -c Release --no-build --verbosity normal --filter "Category!=LongRunning"
